### ISSUE TITLE
bundle.js:52089 Uncaught ReferenceError: mat4_invert is not defined

### ISSUE THREAD

**Issue by tcz001** [hanystudy/coder-from-22nd-century#2]
I tried on chrome, but can't load the host:8301 because of the `Uncaught ReferenceError: mat4_invert is not defined`
the mat4_invert is defined in public/javascripts/webvr/webvr-polyfill.js and built into dist/bundle.js
Could there be any other problem?

**Comment by hanystudy** [comment]
Sounds like a bundling issue, could you please provide version of node/webpack?

**Comment by tcz001** [comment]
node v6.9.1 
webpack 1.14.0

**Comment by hanystudy** [comment]
I've updated to webpack 1.14.0 and it could also work for my side. 
While there is always a note from BABEL, it just **deoptimises** the styling of file webvr-polyfill.js that actually has size of around 230KB. Thus I think the root cause is babel. There are two possible options for us to tackle such issue:

Op 1. Check your version of babel used. Or just move webvr-polyfill.js to inline reference in webpage from current webpack pipeline.

Op 2. Use [experimental chromium builds](https://webvr.info/get-chrome/) or [nightly build firefox](https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly), then try to remove webvr-polyfill.js dependency and try again. I believe there are still additional jobs needed except for just removing webvr-polyfill.js from codebase.

Although we will definitely remove webvr-polyfill.js when webvr is ready on any easy to get browsers. I'll also look at this at spare time.

Thanks for your feedback.

**Comment by tcz001** [comment]
cool I will try that

2016年12月13日 下午11:41，"Han Yi" <notifications@github.com>写道：

**Comment by tcz001** [comment]
I'm using babel-core@6.20.0
After moving webvr-polyfill.js inline, it works now.

**Comment by hanystudy** [comment]
Thanks for reporting your solution.

**Comment by tcz001** [comment]
yes, you can close this issue

2016年12月15日 下午11:29，"Han Yi" <notifications@github.com>写道：
