### ISSUE TITLE
barrel distortion OR 3D room rendering on server side

### ISSUE THREAD

**Issue by tcz001** [hanystudy/coder-from-22nd-century#3]
Right now the delay of processing is unacceptable for a video/conference, when it also consume bunch of power on mobile to do the barrel distortion and 3D rendering with WebGL/WebVR.

WebRTC can be used only for streaming rendered video, and distortion/rendering can be done on server side, even using GPU is possible to make it faster. This can be used for massive market before WebVR is stable/usable for mobile devices. And also can help scaling when cloud service is providing GPU.

The biggest problem will be head tracking, when accelerator data needs to be read by the server side, the network latency could be a trouble, not sure how 100ms~ level delay of network would behave like.

Some references:

https://github.com/tcz001/StereoMac
https://chromium.googlesource.com/chromium/src/media/+/master/capture/video/
https://imgtec.com/blog/speeding-up-gpu-barrel-distortion-correction-in-mobile-vr/

**Comment by hanystudy** [comment]
Good catch! Let me explain our thoughts:

Network delay can be mitigated if you try to use WIFI [hotspot](https://github.com/hanystudy/coder-from-22nd-century#network) between your mobile & PC, and try to use [low resolution in your desktop](https://github.com/hanystudy/coder-from-22nd-century#resolution). We did not focus on resolving delay issue because we believe the content will be produced more frequently by mobile itself and less from third party host such as PC on some day (which **22nd century** means).

C22 has a big difference from [virtual desktop applications](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=steam%20vr%20virtual%20desktop), as it does not simply show **desktop** from traditional PC, it only focus on App/Information (this is why you can choose the specific app window in C22). If you really just want to show high resolution desktop in your HMD, using Vive or even combining it with VNC should be more practical. 

Therefore, C22 is more like idea of [Daydream](https://vr.google.com/daydream/), it should be the **simplest** platform and helping users try to integrate HMD with their daily job. Current architecture is very simple to build and be learned by users, it even allows user to get their nowadays apps in a new world. But it does not mean this is just the future. I surely believe that more developers are going to bring desktop stuff into Daydream (Then 3D viewing should not be the only one thing need to be considered).

Even if Daydream has big success, we won't give up C22 project until everyone can get any info and easy to operate just around human themselves, let alone if it fails finally. We will have roadmap on github later, please provide more feedbacks if you would like to.

I admit that the host end rendering will get better delay & less distortion, but it will be another Vive for us, that's been 21st century stuff already, right?

For your head tracking problem on server side rendering, I'm appreciate if you can do this because developers will debug their apps on PC without trying every types of HMD. Actually Vive supports this feature and works well, but it's supported by quite lots of cables. You can try with wireless network, do not be worried about latency too early.

**Comment by tcz001** [comment]
Valid reason. In that case we can only consider enabling codec like h.264 for streaming.

About the latency I mentioned, it's not related with how the head tracking data can be read, but how far the data can be used by the 3D rendering module to react.

It's just data, I can understand why vive chose cable to do this rather than wireless because it's mainly a wire limitation(which probably will be fixed after 5Gen(60ghz) applied). The only thing we can do is design codec/transportation protocol/rendering strategy for this data specifically.

That's not C22 should consider then. (except rendering strategy)
